export const homeObjeOne = {
    id: 'Tafsiir',
    topLine1:'Tafsiir',
    headline1:'Quran Tafsiir Audio',
    description1: 'By Sh. Umal',
    img1: require('../../images/svg-2.svg').default,
    topLine2:'Tafsiir',
    headline2:'Quran Tafsiir Audio',
    description2: 'By Sh. Umar Farooq',
    img2: require('../../images/svg-2.svg').default,
    topLine3:'Tafsiir',
    headline3:'Quran Tafsiir Audio',
    description3: 'By Sh. Muha. Umar Ali',
    img3: require('../../images/svg-2.svg').default,
};

export const homeObjeTwo = {
    id: 'Hadith',
    topLine1:'Hadith',
    headline1:'Mukhtasar Saxiixul Bukhaari',
    description1: 'Lectures on Sahih Bukhari',
    img1: require('../../images/svg-3.svg').default,
    topLine2:'Hadith',
    headline2:'Mukhtasar Saxiixul Muslim',
    description2: 'Lectures on Sahih Muslim',
    img2: require('../../images/svg-3.svg').default,
    topLine3:'Hadith',
    headline3:' Sunan Tirmidi',
    description3: 'Lectures on Sunan Tirmidi',
    img3: require('../../images/svg-3.svg').default,
};

export const homeObjeThree = {
    id: 'Books',
    topLine1:'Islamic Books',
    headline1:'Riyadu Salixiin',
    description1: 'Lectures Focusing on Hadith Focusing On Ethics, Worship And More.',
    img1: require('../../images/svg-4.svg').default,
    topLine2:'Islamic Books',
    headline2:'Al-Adab Al-Mufrad',
    description2: 'Addressing the Question of Perfecting Muslim Manners',
    img2: require('../../images/svg-4.svg').default,
    topLine3:'Islamic Books',
    headline3:'Buluqul Miraam',
    description3: 'Lectures on the Hadith Collection Buluqul Miraam',
    img3: require('../../images/svg-4.svg').default,
};
